# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb92c5956e366dabccbf7aa56d883046190ee96de0bf9b36121ba8b6a7adfce870020b2ef2bfb10b76888f0bb24ac88542804c125c352257570b8fdb9ca4af40
  admin_password: "manichehaperdido"

test:
  secret_key_base: f86db72a3d79fc8be3600a5bba986c62137b1071c73bc563ff96f6080f8737648e4af00a4d60d73df5efaa7b63168818f7b04a34d6e3e58cc3f9298eec8063a8
  admin_password: "manichehaperdido"

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>  